checks:
    php: true

tools:
    external_code_coverage: false
    php_code_coverage: false
    php_code_sniffer:
        config: { standard: 'Zend' }
    php_changetracking: false
    php_sim: false
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'features/bootstrap/*'
        - 'dev/*'
        - 'var/*'
        - 'lib/*'
        - 'bin/*'
        - 'vendor/*'

build:
    environment:
        php:
            version: 5.4
            ini:
                'always_populate_raw_post_data': '-1'

    dependencies:
        before:
            - date -u +"%Y-%m-%dT%H:%M:%SZ" > /tmp/build-start-time.txt

        override:
            - { command: 'rm -rf ./vendor/ && composer install --no-interaction', idle_timeout: 600 }

    cache:
        directories: [ bin/, ~/.composer/cache ]

build_failure_conditions:
    - 'elements.rating(<= B).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.new.exists'
    - 'project.metric("scrutinizer.quality", < 9.00)'
